pruebaDjango/juegos/urls.py
from django.urls import path


from . import views

app_name = "juegos"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
]

pruebaDjango/polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

pruebaDjango/pruebaDjango/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('juegos/', include('juegos.urls')),
    path("polls/", include("polls.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pruebaDjango/juegos/models.py
from django.db import models

# Create your model of Juego with name, image, description, number_players
class Juego(models.Model):
    juego_name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='juego_images/') 
    description = models.TextField() 
    number_players = models.IntegerField()

     

pruebaDjango/polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self) -> str:
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self) -> str:
        return self.choice_text
# The code is straightforward. Each model is represented by a class that subclasses django.db.models.Model. Each model has a number of class variables, each of which represents a database field in the model.

pruebaDjango/juegos/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Juego
# quiere herencia tipo layout en templates y paginación

class IndexView(generic.ListView):
    template_name = "juegos/index.html"


class DetailView(generic.DetailView):
    model = Juego
    template_name = "juegos/detail.html"

pruebaDjango/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice


def index(request):
    mi_html = [f"<li>{q.question_text}</li>" for q in Question.objects.all()]
    return HttpResponse(mi_html)

def detail(request, question_id):
    return HttpResponse("You're looking at question %s." % question_id)

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

from django.shortcuts import get_object_or_404, render


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})    

pruebaDjango/juegos/templates/detail.html
<!-- juego_detail.html -->
<h2>{{ juego.juego_name }}</h2>
<img src="{{ juego.image.url }}" alt="{{ juego.juego_name }}">
<p>{{ juego.description }}</p>
<p>Number of players: {{ juego.number_players }}</p>

pruebaDjango/juegos/templates/index.html
{% if juego_list %}
    <ul>
    {% for juego in juego_list %}
        <li><a href="{% url 'juegos:detail' juego.id %}">{{ juego.juego_name }}</a></li>
        <!-- lo del {{juego.id}} es como un php echo, imprime el valor de la variable-->
        <!-- -->
        <!--<li><a href="{% url 'juegos:detail' juego.id %}">{{ juego.juego_name }}</a></li> esto hace una función-->
    {% endfor %}
    </ul>
{% else %}
    <p>No juegos are available.</p>
{% endif %}

pruebaDjango/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>
            <h1>{{ question.question_text }}</h1>
        </legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

pruebaDjango/polls/templates/polls/index.html
{% if question_list %}
    <ul>
    {% for question in question_list %}
        <li><a href="/polls/{{question.id}}">{{ question.question_text }}</a></li>
        <!-- lo del {{question.id}} es como un php echo, imprime el valor de la variable-->
        <!-- -->
        <!--<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li> esto hace una función-->
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

pruebaDjango/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>